### PR TITLE
Expose put attachment data

### PR DESCRIPTION
**Pull request by shribe**
The ability to add attachments from in-memory data instead of an on-disk file was not exposed in the Mail module. I think this was an oversight?

### CODE REVIEW

**Comment by bcardarella** [comment]
Overall looks good. Thanks for adding the missing API. Once the failing tests are addressed this should be good to merge

**Comment by shribe** [comment]
I don't understand the failing test because when I run `mix test` my new tests pass. (Although 4 of the pre-existing ones fail, even without these changes.) It just looks like somewhere there's an inconsistency between using an atom or a string for the `content-disposition` key. But the fact that I don't see this failure makes me hesitant to look for it. Can you take a look?

**Comment by shribe** [comment]
Aslo, after I made this pull request, I noticed issues #40 & #41, and the reference to adding it to the docs. This functionality is already shown in the Multi-Part example in the README, so I didn't notice that it's *NOT* in the docs.

**Comment by bcardarella** [comment]
I fixed the tests and merged in your commits: https://github.com/DockYard/elixir-mail/pull/71

**Pull request closed without merging**
