### PR TITLE
Parse unstructured header field bodies, RFC2822 §2.2.1

### PR DESCRIPTION
**Pull request by andrewtimberlake**
Parsing unstructured header fields resulted in a parse error.
This change identifies three structured fields, Received, Content-Type, and Content-Disposition and then parses any others as undstructured—the field body is left unchanged.

### CODE REVIEW

**Comment by bcardarella** [comment]
Thanks!

**Comment by bcardarella** [comment]
This PR was green but it went red when merged: https://travis-ci.org/DockYard/elixir-mail/builds/161916626

Can you look into this before I merge in the other PRs? Don't want to merge branches into a red master.

**Comment by andrewtimberlake** [comment]
@bcardarella They are all green on https://travis-ci.org/DockYard/elixir-mail/pull_requests
This one seems merged so I’m not sure what to do from here?

Each pull request I submitted was rebased against the DockYard master branch but they may conflict once each is committed. I’m happy to rebase other pull requests after each you accept.
I’m in South Africa so I’m awake for another 2 hours otherwise I’ll pick things up tomorrow.

**Comment by bcardarella** [comment]
Strange, I just reran travis and it is now green: https://travis-ci.org/DockYard/elixir-mail/builds/161916626

**Pull request merged**
