### PR TITLE
Change to storing headers as text instead of atoms

### PR DESCRIPTION
**Pull request by andrewtimberlake**
This is the beginning of work toward dealing with #16 and a request for comments.

Instead of accessing headers directly as `mail.headers.content_type`, they are now accessed via functions, `Mail.Message.get_header(:content_type)` and `mail.headers.to` is now `Mail.get_to(mail)`
There is still much code which accesses headers directly which need to be cleaned up.

### CODE REVIEW

**Comment by bcardarella** [comment]
I am thinking we drop the need for atoms all together. So `Mail.Message.get_header("content_type")` instead. Thoughts?

**Comment by andrewtimberlake** [comment]
I’m normalizing the header name. They are stored as lowercase strings.
I then normalize the key when retrieving the header
`Mail.Message.get_header(:content_type)`, `Mail.Message.get_header("content-type")` and `Mail.Message.get_header("Content-Type")` are all equivalent.

**Comment by andrewtimberlake** [comment]
RFC2822 §3.6
> It is important to note that the header fields are not guaranteed to
   be in a particular order.  They may appear in any order, and they
   have been known to be reordered occasionally when transported over
   the Internet.  However, for the purposes of this standard, header
   fields SHOULD NOT be reordered when a message is transported or
   transformed.  More importantly, the trace header fields and resent
   header fields MUST NOT be reordered, and SHOULD be kept in blocks
   prepended to the message.  See sections 3.6.6 and 3.6.7 for more
   information.

The current implementation of `%Mail.Message` uses a `Map` which doesn’t allow mail to honor this.

I suggest changing to a list of two element tuples. The first element would be the header name and the second the header value.

    %Mail.Message{headers: [
      {"Return-Path", "<me@example.com>"},
      {"Received", "first"},
      {"Received", "first"},
      #...
    ]}

We can then have functions to retrieve them.

    iex> Map.Message.get_header(message, "Return-Path")
    ["<me@example.com>"]
    iex> Map.Message.get_header(message, "Received")
    ["first", "second"]

Thoughts?

**Comment by bcardarella** [comment]
Merge conflits

**Comment by bcardarella** [comment]
Thanks!

**Pull request merged**
