### PR TITLE
fix reorganize/1: do not return nil for messages without text parts

### PR DESCRIPTION
**Pull request by serpent213**
## Changes proposed in this pull request

enable rendering of multipart messages that do not contain text parts

### CODE REVIEW

**Comment by bcardarella** [comment]
Can you articulate your usecase and provide a test?

**Comment by serpent213** [comment]
Is that sufficient? One of tests fails without the initial patch.

**Comment by serpent213** [comment]
It seems ``Mail.TestAssertions`` takes care of normalising the boundaries.

**Comment by serpent213** [comment]
Any news on this? Things for me to change?

**Comment by bcardarella** [comment]
Sorry, lost track. Thanks for pinging me on it.

**Pull request merged**
