### PR TITLE
Fix bug parsing addresses with a comment

### PR DESCRIPTION
**Pull request by andrewtimberlake**
Legacy address spec allowed a comment in the address `Name <address> (comment)`.
This allows parsing addresses with a comment—but ignores the comment

Note, this patch follows #50

### CODE REVIEW

**Comment by bcardarella** [comment]
Merge conflicts

**Comment by bcardarella** [comment]
Merge conflicts

**Comment by bcardarella** [comment]
Merge conflicts

**Comment by andrewtimberlake** [comment]
This was committed with #49

**Pull request closed without merging**
