### PR TITLE
fix recipient regex

### PR DESCRIPTION
**Pull request by princemaple**
```elixir
# currently
iex> Regex.scan(~r/\s*"?(.*?)"?\s*?<?([^\s]+@[^\s>]+)>?,?/, "abc<def@xyz.com>")  
[["abc<def@xyz.com>", "", "abc<def@xyz.com"]]

# with the fix
iex> Regex.scan(~r/\s*"?(.*?)"?\s*?<?([^<\s]+@[^\s>]+)>?,?/, "abc<def@xyz.com>") 
[["abc<def@xyz.com>", "abc", "def@xyz.com"]]
```

### CODE REVIEW

**Comment by andrewtimberlake** [comment]
Hi @princemaple please update this pull request with a test that shows the problem that would fail without the fix. Thanks.

**Comment by princemaple** [comment]
Hi @andrewtimberlake , updated. Additionally added a `,`, to the exclusion list to avoid the regex being too greedy and match the comm with the `[^\s>]+` part.

**Comment by princemaple** [comment]
Will there be a new release any time soon?

**Comment by princemaple** [comment]
I promise it's my last time asking... :wink:

**Comment by bcardarella** [comment]
@princemaple I'l go through it on Saturday and check to see about a release. Sorry I let it drag. Been bogged down on other stuff

**Comment by princemaple** [comment]
Thanks for the reply! Appreciate it.

**Comment by andrewtimberlake** [comment]
0.2.2 has just been released

**Comment by princemaple** [comment]
@andrewtimberlake thanks! Great to see activity on this nice little lib.

**Pull request merged**
