### PR TITLE
Refactor mail parser

### PR DESCRIPTION
**Pull request by andrewtimberlake**
This is a refactor that changes the parser from relying on Regex to reading and parsing the mail line by line.

This patch follows #52

### CODE REVIEW

**Comment by bcardarella** [comment]
Merge conflicts

**Comment by bcardarella** [comment]
I was thinking about actually using Erlang's `leex` library to build a tokenizer and parser. Might be overkill but it will probably be the most comprehensive solution. Thoughts?

**Comment by andrewtimberlake** [comment]
Might be. I have been running my code against a corpus of 4000+ existing emails and it’s working well.

**Comment by bcardarella** [comment]
Merge conflits

**Comment by andrewtimberlake** [comment]
This was committed with #49

**Pull request closed without merging**
